version: "3.7"
services:
    app:
        build:
            args:
                user: www
                uid: ${UID:-1000}
            context: ./
            dockerfile: Dockerfile
        container_name: test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: test-db
        restart: unless-stopped
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    nginx:
        build:
            context: ./
            dockerfile: ./.docker/nginx/DockerFile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: test-nginx
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
